config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pools
  resources :series

  root 'welcome#index'
end

app/models/commissioner.rb
class Commissioner < ActiveRecord::Base
  belongs_to :user
  has_one :pool
end

app/models/nba_team.rb
class NbaTeam < ActiveRecord::Base
end

app/models/pool.rb
class Pool < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :commissioner
  has_many :series
end

app/models/series.rb
class Series < ActiveRecord::Base
  ROUNDS = ['1', '2', 'conference_finals', 'finals']

  belongs_to :user
  belongs_to :pool

  validates :round, presence: true
  validates :away_team_wins, presence: true, on: :update
  validates :home_team_wins, presence: true, on: :update
  validates :user_id, presence: true
    self
      .joins('INNER JOIN nba_teams ON nba_teams.team_id = series.away_team_id')
      .where('nba_teams.conference = ?', conference)
      .where(round: '1')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :pools
  has_many :commissioners
  has_many :series

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    picks_path
  end

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
 end

end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController

  def index
    @pools = Pool.all
  end

  def new
    @pool = Pool.new
  end

  def create
    if pool_creation_transaction
      flash[:notice] = "Your pool has been created"
      redirect_to @pool
    else
      flash[:error] = "There was a problem creating your pool.  Please try again."
      render :new
    end
  end

  def show
    @pool = Pool.find(params[:id])
  end

  private

  def pool_params
    params.require(:pool).permit(:name)
  end

  def pool_creation_transaction
    ActiveRecord::Base.transaction do
      begin
        @pool = current_user.pools.create!(pool_params)
        commissioner = current_user.commissioners.create!
        @pool.update!(commissioner: commissioner)
      rescue Exception => e
        logger.error "User #{current_user.id} experience #{e.message} when trying to create a new pool"
        false
      end
    end
  end

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController

  def index
    @east_series     = Series.for(current_user, Series::ROUNDS.first, 'East')
    @west_series     = Series.for(current_user, Series::ROUNDS.first, 'West')

    @round_one_east_picks     = @east_series.where('home_team_wins IS NOT null').where('away_team_wins IS NOT null')
    @round_one_west_picks     = @west_series.where('home_team_wins IS NOT null').where('away_team_wins IS NOT null')
  end

  def new
    @series = current_user.series.build
  end

  def create
    @series = current_user.series.build(series_params)

    if @series.save
      redirect_to series_index_path
    else
      flash[:error] = "There was a problem saving your pick.  Please try again."
      render :new
    end
  end

  def edit
    @series = Series.find(params[:id])
  end

  def update
    @series = Series.find(params[:id])

    if @series.update(series_params)
      redirect_to series_index_path
    else
      flash[:error] = "There was a problem updating our pick.  Please try again."
      render :edit
    end
  end

  private

  def series_params
    params.require(:series).permit(:user_id, :away_team_wins, :home_team_wins, :points_awarded, :pool_id, :next_round_competitor_series_id, :away_team_id, :home_team_id, :round)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NbaPickem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

   <div>
     <% if current_user %>
       Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
     <% else %>
       <%= link_to "Sign In", new_user_session_path %> or
       <%= link_to "Sign Up", new_user_registration_path %>
     <% end %>
   </div>

   <div>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% elsif flash[:error] %>
      <%= flash[:error] %>
    <% end %>
   </div>

<%= yield %>

</body>
</html>

app/views/picks/_form.html.erb
<%
  series = @pick.series || Series.find(params[:series] || params[:pick][:series_id])
  away   = series.away_team_id.titleize
  home   = series.home_team_id.titleize
%>

<h4><%= away %> vs. <%= home %></h4>

<div>
  <%= simple_form_for @pick do |f| %>
    <p><%= f.input :away_team_wins, label: "#{away} wins" %></p>
    <p><%= f.input :home_team_wins, label: "#{home} wins" %></p>
       <%= f.input :series_id, as: :hidden, input_html: { value: "#{series.id}" } %>
    <p><%= f.button :submit %> <%= link_to 'Cancel', picks_path %></p>
  <% end %>
</div>

app/views/pools/index.html.erb
<h2>Current Pools</h2>

<table>
  <tbody>
    <tr>
      <td>Name</td>
      <td>Members</td>
    </tr>

    <% @pools.each do |pool| %>
      <tr>
        <td><%= pool.name.titleize %></td>
        <td><%= pool.users.count %></td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/pools/new.html.erb
<%= simple_form_for @pool do |f| -%>
  <%= f.input :name, label: 'Pool name' -%>
  <%= f.button :submit -%>
<% end -%>

app/views/pools/show.html.erb
<h2><%= @pool.name.titleize %> Pool</h2>
<h4>Pool members</h4>

<% @pool.users.each do |user| %>
  <p><%= user.full_name %></p>
<% end %>

app/views/series/_form.html.erb
<%
  away = series.away_team_id.titleize
  home = series.home_team_id.titleize
%>

<h4><%= away %> vs. <%= home %></h4>

<div>
  <%= simple_form_for @series do |f| %>
    <p><%= f.input :away_team_wins, label: "#{away} wins" %></p>
    <p><%= f.input :home_team_wins, label: "#{home} wins" %></p>
       <%= f.input :series_id, as: :hidden, input_html: { value: "#{series.id}" } %>
    <p><%= f.button :submit %> <%= link_to 'Cancel', series_index_path %></p>
  <% end %>
</div>

app/views/series/edit.html.erb
<%= render partial: 'form', locals: { series: @series } %>

app/views/series/index.html.erb
<% if @east_series.present? %>

  <h2>Round <%= @east_series.first.round %></h2>

  <h3>East Conference</h3>
  <% @east_series.each do |game| %>
    <div class="east">
      <h3><%= game.away_team_id.titleize -%> vs. <%= game.home_team_id.titleize -%></h3>

      <% if game.home_team_wins.present? && game.away_team_wins.present? %>
        <p><%= link_to "#{game.away_team_id.titleize} : #{game.away_team_wins}", edit_series_path(game) %></p>
        <p><%= link_to "#{game.home_team_id.titleize} : #{game.home_team_wins}", edit_series_path(game) %></p>
      <% else %>
        <p><%= link_to "Make your picks", edit_series_path(game) %></p>
      <% end %>

    </div>
  <% end %>

  <h3>West Conference</h3>
  <% @west_series.each do |game| %>
    <div class="west">
      <h3><%= game.away_team_id.titleize -%> vs. <%= game.home_team_id.titleize -%></h3>

      <% if game.home_team_wins.present? && game.away_team_wins.present? %>
        <p><%= link_to "#{game.away_team_id.titleize} : #{game.away_team_wins}", edit_series_path(game) %></p>
        <p><%= link_to "#{game.home_team_id.titleize} : #{game.home_team_wins}", edit_series_path(game) %></p>
      <% else %>
        <p><%= link_to "Make your picks", edit_series_path(game) %></p>
      <% end %>

    </div>

  <% end %>

  <% if @round_one_east_picks.present? || @round_one_west_picks.present? %>

    <h2>Round 2</h2>

  <% end %>

<% end %>

app/views/series/new.html.erb
<%= render partial: 'form', locals: { series: @series } %>

app/views/welcome/index.html.erb
<%= link_to "Create a new pool", new_pool_path %>